backend:
  name: github
  repo: 21r11a1208/Portfolio
  branch: main
  base_url: https://www.anish.works
  auth_endpoint: api/decap/auth
local_backend: true
media_folder: public/uploads
public_folder: /uploads
collections:
  - name: pages
    label: Pages
    files:
      - name: placeholder
        label: Placeholder
        file: content/placeholder.json
        fields:
          - { name: title, label: Title, widget: string }
